import "./globals.css";
import type { Metadata } from "next";
import { Cabin_Condensed } from "next/font/google";

const cabinCondensed = Cabin_Condensed({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EdTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={cabinCondensed.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
